#SPDX-License-Identifier: MIT-0
---
# defaults file for secrets
secrets_manager_region: "eu-north-1"
secrets_manager_name: "petclinic_db_credentials"
secrets_env_dir: "/opt/petclinic_db_credentials"
secrets_env_file: "/opt/petclinic_db_credentials/app_secrets.env"

secrets_env_mapping:
  DB_USERNAME: "username"
  DB_PASSWORD: "password"
  DB_HOST: "host"
  DB_NAME: "dbname"
  DB_PORT: "port"

