services:
  petclinic:
    image: ${TF_ECR_URL}:latest
    container_name: petclinic-app
    restart: always
    ports:
      - "8080:8080"

    env_file:
      - app_secrets.env

    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:db/mysql/schema.sql
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath:db/mysql/data.sql
      - SPRING_SQL_INIT_CONTINUE_ON_ERROR=false

    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "3"
